### PR TITLE
Adding some more shaders to resolve logspam.

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
I also found that using my recompiled DLL (with new or old shader bundles) resolved the issue reported in #11.  The only changes I'd made (besides some code to load a Dx11 bundle, but that wasn't active because that bundle didn't work) was to compile against KAS (using the legacy DLL, from version 0.6.x...this will require some changes when KAS 1.0 is fully released) and Procedural Fairings as well as KSP itself, which resulted in a DLL of ~80 kb vs. ~50 from 0.0.9.2.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
Please, next time do NOT change the .version file.  I have a process that I follow, this can mess it up.
But, thanks for the PR

**Comment by linuxgurugamer** [comment]
Anyway, thanks, it's going to be a few days before I can rebuild and release.

**Comment by linuxgurugamer** [comment]
PLEASE DO NOT PUSH CHANGES TO MY DEPLOY SCRIPTS

**Comment by Kerbas-ad-astra** [comment]
Sorry, I thought I kept all the development environment changes out of the commit.  Which one did I miss?

E: I see now.  Sorry I let that slip into the commit.

**Comment by Starstrider42** [comment]
There's still a lot of spam from stock fairings. Was that out of scope?

    [WRN 15:29:36.097] [KVV] LoadShaders KVrVesselShot No replacement for KSP/Bumped Specular (Cutoff) (UnityEngine.Shader) in fairingSize2 (Part)/*/FairingPanel (UnityEngine.MeshRenderer)
    [WRN 15:29:36.097] [KVV] LoadShaders KVrVesselShot No replacement for KSP/Specular (Cutoff) (UnityEngine.Shader) in fairingSize2 (Part)/*/FairingPanel (UnityEngine.MeshRenderer)

**Comment by Kerbas-ad-astra** [comment]
That's definitely in scope.  I just didn't know it was an issue until now.  :)
E: Unfortunately, those shaders don't seem to be available anywhere (not in the KSP PartTools nor previously extracted by someone else), so I can't add them to the bundle like I did the shaders from your first report.

At the very least, it would improve matters slightly to add a condition to [the Update() function](https://github.com/linuxgurugamer/KronalVesselViewer/blob/e7972a12120071fcb5cededf9da24d33b7213a65/KronalVesselViewer/KVrVesselShotUI.cs#L102) such that the screenshot is only updated while the KVV window is open.

**Comment by linuxgurugamer** [comment]
The csproj and the .version file

Not a big deal, it was easy to fix.

Thanks for the pr

**Comment by linuxgurugamer** [comment]
FYI, I wasn't aware that the release build was bad (my fault, I didn't read your comment in the other issue).  It's now fixed with a manual build until I figure out what is wrong.

**Pull request merged**
