### PR TITLE
Release candidate for 1.8

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
Most of the changes should be self-explanatory, but I tinkered a little with the project and TT files in ways that should fit seamlessly into your dev environment but I should let you know up-front about them.
- I removed the "EnvDTE" line from AssemblyVersion.tt.  I couldn't compile the project until I did, and I see you've removed it in some of your other repos (e.g. linuxgurugamer/ScienceAlert@dd1b2a0c864bba6e7a108ddbe0df7939dbb38ecd).
- I edited the csproj file to refer to the non-legacy KAS DLL (the legacy DLL and parts have been completely deprecated from the KSP 1.8 releases), and added a reference to the KSPDev_Utils DLL that I've added to the Assets/Plugins folder of this repo (which was necessary to support the new KAS parts).

Everything's working on my Windows machine, so if it works for you on Linux I think it will be OK to release.

Full changelog:

- Recompiled shader bundles with Unity 2019.2.2f1 and PartTools for KSP 1.8.
- Removed unnecessary "EnvDTE" line from AssemblyVersion.tt.
- Disabled color adjust and FXAA filters (they don't seem to work with DX11 -- I'd like to figure these out, but they're not vital functions of the mod so I'm okay with releasing without them).
- Disabled "new vessel", "load vessel", and "switch editor" buttons while vessel is in Exploded view to prevent exceptions.
- Updated KAS support to use new (non-Legacy) modules and DLL.
- Fixed a text error in the fairing options.

Still todo:
- [ ] Get "hide front half" option for Procedural Fairings mod working again.

### CODE REVIEW

**Comment by Kerbas-ad-astra** [comment]
Added a couple more commits:
- Localization
- Fixes for decoupler (resolves #15 and #16)

**Comment by deiferni** [comment]
great thanks ✨! i could test and confirm this if you want, is there some kind of prerelease around? having trouble building the mod at the moment.

**Comment by intervisionlord** [comment]
Doesn't work for me - there is no button in toolbar to activate the viewer.

**Comment by Kerbas-ad-astra** [comment]
Can you share with me the DLL you compiled?

**Comment by intervisionlord** [comment]
I am just ~~walked by~~ try to test version from pull request

**Comment by Kerbas-ad-astra** [comment]
This pull request just has the source code that I'm proposing to change.  It needs to be compiled into a DLL for the game to actually load it.  This pull request doesn't have that DLL in it, so unless you opened up the code in Visual Studio (or some other C# development environment) and compiled it yourself, you wouldn't have a DLL and so there wouldn't be anything for KSP to run.

**Comment by intervisionlord** [comment]
Could you, please, compile it for testing or provide some information about ways of compilation this source (sry, but C# is not my strong side (as English ;))
The point is that i'd like to use this mod in KSP 1.8.1 but there are no ready versions for it. (Even unstable)

**Comment by Kerbas-ad-astra** [comment]
Since I was able to recompile Procedural Fairing for KSP 1.8 easily enough, I've re-enabled (un-disabled) this mod's support for it.  Still needs adjusting because the 'hide front half' option isn't doing anything anymore, probably because of a change in Procedural Fairings.

@intervisionlord, if you have Visual Studio, you can clone this repository onto your personal computer and make a file called KronalVesselViewer.csproj.user (in the same place as KronalVesselViewer.csproj, in the KronalVesselViewer sub-folder with all of the .cs files).  The file should contain the following:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <KSPDIR>path\to\your\KSP\1.8.1\install</KSPDIR>
  </PropertyGroup>
</Project>
```
You will then need to install Click Through Blocker, KAS, ToolbarControl, and Procedural Fairings```*``` into that KSP install.  After you've done all of that, you can open KronalVesselViewer.sln and use the "Build Solution" command from the Build menu to build the DLL.  It will end up in (wherever you put the repository)/KronalVesselViewer/bin/(whichever version you built)/KronalUtils.dll.  You'll probably get some error about "deploy.bat" and "buildRelease.bat" not being found, but you can ignore those since that's just for making a nice package for release.

You will then install Kronal Vessel Viewer from the "GameData" subdirectory of this repo into your KSP GameData folder, and copy the KronalUtils.dll you just compiled into (GameData)/KronalVesselViewer/Plugins.  You should be all set!

```*``` Except that Procedural Fairings hasn't been updated for KSP 1.8 yet, so you'll need to do a similar procedure (but not quite the same, because their build process isn't quite the same as linuxgurugamer's; you'll have to manually re-target the reference DLLs) for that mod before you can compile this mod.

**Comment by intervisionlord** [comment]
Great respect and thanks! =)

**Comment by Kerbas-ad-astra** [comment]
Closing for now while I figure out the 'hide one half' option...it's either vanishing both of them or neither.

**Pull request closed without merging**
